[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "r3"
description = "Repository of Reproducible Research"
authors = [
    {name = "Matthias Tangemann", email = "matthias.tangemann@bethgelab.org"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "click~=8.1.3",
    "executor~=23.2",
    "pyyaml~=6.0",
]
dynamic = ["version"]


[project.optional-dependencies]
dev = [
    "black==22.10.0",
    "flake8==6.0.0",
    "flake8-bugbear==22.10.27",
    "isort==5.10.1",
    "mypy==0.991",
]


[project.scripts]
r3 = "r3.cli:cli"


[tool.isort]
profile = "black"


[[tool.mypy.overrides]]
module = [
    "executor",
]
ignore_missing_imports = true
